#!/usr/bin/env bash
packages=(
  bin
  zsh
  nix
  ghostty
  ghostty-linux
  git
  nvim
  oh-my-posh
  tmux
  zsh-plugins
  ssh
  ssh-linux
  personal/git
)

PKGS="${packages[@]}" ./install/install

ln -sf "/opt/1Password/op-ssh-sign" "$HOME/.local/bin/op-ssh-sign"

systemctl --user enable --now ghostty-override-check.path ghostty-override-check.timer

sudo stow -Rt / cachyos
