#!/usr/bin/env bash
packages=(
  bin
  zsh
  nix
  ghostty
  git
  nvim
  oh-my-posh
  tmux
  zsh-plugins
  ssh
  ssh-linux
  claude
  personal/git
)

PKGS="${packages[@]}" ./install/install

ln -sf "/opt/1Password/op-ssh-sign" "$HOME/.local/bin/op-ssh-sign"

sudo stow -Rt / cachyos
