#!/bin/env bash
packages=(
  bin
  zsh
  hyprland
  ghostty
  git
  jj
  nvim
  oh-my-posh
  tmux
  zsh-plugins
  personal/git
  personal/jj
  personal/ssh
)

PKGS="${packages[@]}" ./install/install

ln -sf "/opt/1Password/op-ssh-sign" "$HOME/.local/bin/op-ssh-sign"
