#!/usr/bin/env bash
TRGT="$HOME"

for PKG in $PKGS
do
  stow_pkg="$PKG"
  if [[ "$PKG" == */* ]]; then
    pushd "$(dirname $PKG)" >/dev/null
    stow_pkg="$(basename $PKG)"
  fi
  extra_flags=""
  if [[ -f "$stow_pkg/.no-fold" ]]; then
    extra_flags=" --no-folding"
  fi
  stow -Rt "$TRGT"$extra_flags "$stow_pkg"
  if [[ "$PKG" == */* ]]; then
    popd >/dev/null
  fi
done

