#!/usr/bin/env bash
packages=(
  bin
  zsh
  nix
  ghostty
  git
  nvim
  oh-my-posh
  tmux
  zsh-plugins
  ssh
  ssh-macos
  claude
  personal/git
)

PKGS="${packages[@]}" ./install/install

ln -sf "/Applications/1Password.app/Contents/MacOS/op-ssh-sign" "$HOME/.local/bin/op-ssh-sign"
