#!/usr/bin/env bash
packages=(
  bin
  zsh
  nix
  git
  git-wsl
  jj
  nvim
  oh-my-posh
  tmux
  zsh-plugins
  containers
  personal/git
  personal/git-work
  personal/jj
  personal/jj-work
  personal/zsh-work
)

PKGS="${packages[@]}" ./install/install

# Command-line tools (nix/.config/toolchains/profiles/). Only warns for a set
# already added; `nix profile upgrade --all` picks up changes.
toolchains="path:$(realpath "$HOME/.config/toolchains")"
nix profile add "$toolchains#global" "$toolchains#work"

# podman's own user units (podman.socket for Testcontainers), from the profile so
# they follow upgrades; run `systemctl --user daemon-reload` after one
systemctl --user link "$HOME"/.nix-profile/lib/systemd/user/podman.{socket,service}

# TODO: This can be done for all WSL instances
winHome=$(/mnt/c/Windows/System32/cmd.exe /C "echo %USERPROFILE%")
winHome=$(wslpath -au "$winHome" | tr -d '\r')

ln -sf "$winHome/AppData/Local/Microsoft/WindowsApps/op-ssh-sign-wsl.exe" "$HOME/.local/bin/op-ssh-sign"
# The following is so Oh-My-Posh can see that it is a git directory. DO NOT BIND TO GIT (without extension)
ln -sf "/mnt/c/Program Files/Git/cmd/git.exe" "$HOME/.local/bin/git.exe"

sudo stow -Rt /etc wsl

# TODO: What do we do about the ssh configs that need to be stored/updated on windows
